name:configuration variable demo
on:
  workflow_dispatch
env:
  cloud: google-cloud
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "First env demo"
        run: echo "My $cloud say $Greeting! with the day ${{ vars.weekday }}"
        env:
          first_name: Mahesh
