name: demo on variables

on: 
  workflow_dispatch
env:
  cloud: google-cloud
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "First env demo"
        run: echo "My $cloud say $Greeting!"
        env:
          first_name: Mahesh
